[project]
name = "trip-scheduler kata python"
version = "0.1.0"
description = "Refactoring kata"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.3.4",
]


[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = [
  "./src"
]